### ISSUE TITLE
Full support for ADS-B Exchange

### ISSUE THREAD

**Issue by marcelstoer** [jeanralphaviles/dump1090-docker#1]
The `webmonkey/docker-adsbexchange` only runs `socat`.  That's quite a bit less than what you are supposed to do according to https://www.adsbexchange.com/how-to-feed/ to fully support them.

**Comment by marcelstoer** [comment]
I'm working on this here: https://github.com/marcelstoer/adsbexchange-docker

The two images for MLAT & feeder are ready but currently need to be built on the device. I'll be implementing CI for those to be available on Docker Hub soon.

**Comment by marcelstoer** [comment]
The images are now ready on Docker Hub: marcelstoer/adsbexchange-docker-feed and marcelstoer/adsbexchange-docker-mlat

**Comment by jeanralphaviles** [comment]
Hey, sorry for the delay. My laptop got stolen on vacation and couldn't get to this. I appreciate you making improvements.

> That's quite a bit less than what you are supposed to do according to https://www.adsbexchange.com/how-to-feed/ to fully support them.

The socat is what you're doing in `marcelstoer/adsbexchange-docker-feed`, but having proper MLAT support with https://github.com/adsbxchange/mlat-client.git in `marcelstoer/adsbexchange-docker-mlat` is great.

Once you've got automatic Docker builds, ping this issue and we can update this repo's README to use your implementations instead. Everything was working perfect for me with adsbexchange-docker-feed.

```shell
$ docker run --rm -d --link dump1090:decoder --name adsb-exchange --env RECEIVER_PORT=30005 --env INPUT=decoder:30005 marcelstoer/adsbexchange-docker-feed
```

But I get a fetch error with adsbexchange-docker-mlat

```shell
docker run --rm -d -e "INPUT=decoder:30005" -e "MLAT_RESULTS=decoder:30104" -e "RECEIVER_LATITUDE=12.345678" -e "RECEIVER_LONGITUDE=12.345678" -e "RECEIVER_ALTITUDE=0" -e "RECEIVER_NAME=my-fantastic-ADS-B-receiver" --link dump1090:decoder --name adsbexchange-mlat adsbexchange-docker-mlat
docker: Error response from daemon: pull access denied for adsbexchange-docker-mlat, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.
See 'docker run --help'.
```

Can you fix up the permissions on that one?

**Comment by marcelstoer** [comment]
Sorry about your laptop loss; would devastate me.

> The socat is what you're doing

Yes, `socat` is still `socat` but having log output and a retry-on-connection-loss is essential for me.

> Once you've got automatic Docker builds, ping this issue and we can update this repo's README to use your implementations instead.

My self-imposed ambition/requirement was to have multi-arch images. The recent introduction of Docker buildx was a revelation and I'm still in awe how they pulled this off (currently working on a [blog post](https://frightanic.com/computers/docker-buildx-the-best-thing-since-sliced-bread/) about it). Once they add this to the auto-builds on Docker Hub I'll enable it. Until then I'll run and push from my laptop - a breeze.

> I get a fetch error with adsbexchange-docker-mlat

Your forgot my name 😉 Try with `marcelstoer/adsbexchange-docker-mlat`. https://hub.docker.com/repository/docker/marcelstoer/adsbexchange-docker-mlat exists and is public; works for me.

**Comment by jeanralphaviles** [comment]
@marcelstoer updated the readme to use his images in #5. Closing this out.
